# .travis.yml for R CDADataSims

language: r
warnings_are_errors: false
sudo: required

notifications:
  email:
    - ddrackham@gmail.com

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
